import type { OverviewSankeyGraphDto } from "$lib/overview/types.ts";

export function overviewSankeyPrototype(): OverviewSankeyGraphDto {
  return {
    nodes: [
      { id: "root:asset", label: "資產", level: 0, tone: "asset" },
      { id: "root:liability", label: "負債", level: 0, tone: "liability" },
      { id: "kind:bank", label: "銀行", level: 1, tone: "asset" },
      { id: "kind:fund", label: "基金", level: 1, tone: "asset" },
      { id: "kind:brokerage", label: "券商", level: 1, tone: "asset" },
      { id: "kind:crypto", label: "加密資產", level: 1, tone: "asset" },
      { id: "kind:foreign", label: "外幣", level: 1, tone: "asset" },
      { id: "kind:credit-card", label: "信用卡", level: 1, tone: "liability" },
      { id: "kind:loan", label: "貸款", level: 1, tone: "liability" },
      { id: "account:bank:cathay", label: "國泰世華", level: 2, tone: "asset" },
      { id: "account:fund:yuanta", label: "元大基金", level: 2, tone: "asset" },
      { id: "account:brokerage:fubon", label: "富邦證券", level: 2, tone: "asset" },
      { id: "account:crypto:maicoin", label: "MaiCoin", level: 2, tone: "asset" },
      { id: "account:foreign:cathay", label: "國泰外幣", level: 2, tone: "asset" },
      { id: "account:credit-card:ctbc", label: "中信信用卡", level: 2, tone: "liability" },
      { id: "account:loan:fubon", label: "富邦貸款", level: 2, tone: "liability" },
      { id: "position:yuanta:fund-a", label: "元大高股息", level: 3, tone: "asset" },
      { id: "position:yuanta:fund-b", label: "元大台灣50", level: 3, tone: "asset" },
      { id: "position:fubon:2330", label: "台積電", level: 3, tone: "asset" },
      { id: "position:maicoin:btc", label: "Bitcoin", level: 3, tone: "asset" },
    ],
    links: [
      { source: "root:asset", target: "kind:bank", value: 717_518, tone: "asset" },
      { source: "root:asset", target: "kind:fund", value: 1_491_341, tone: "asset" },
      { source: "root:asset", target: "kind:brokerage", value: 420_000, tone: "asset" },
      { source: "root:asset", target: "kind:crypto", value: 98_000, tone: "asset" },
      { source: "root:asset", target: "kind:foreign", value: 53_407, tone: "asset" },
      { source: "root:liability", target: "kind:credit-card", value: 6_851, tone: "liability" },
      { source: "root:liability", target: "kind:loan", value: 1_520_275, tone: "liability" },
      { source: "kind:bank", target: "account:bank:cathay", value: 717_518, tone: "asset" },
      { source: "kind:fund", target: "account:fund:yuanta", value: 1_491_341, tone: "asset" },
      { source: "kind:brokerage", target: "account:brokerage:fubon", value: 420_000, tone: "asset" },
      { source: "kind:crypto", target: "account:crypto:maicoin", value: 98_000, tone: "asset" },
      { source: "kind:foreign", target: "account:foreign:cathay", value: 53_407, tone: "asset" },
      { source: "kind:credit-card", target: "account:credit-card:ctbc", value: 6_851, tone: "liability" },
      { source: "kind:loan", target: "account:loan:fubon", value: 1_520_275, tone: "liability" },
      { source: "account:fund:yuanta", target: "position:yuanta:fund-a", value: 900_000, tone: "asset" },
      { source: "account:fund:yuanta", target: "position:yuanta:fund-b", value: 591_341, tone: "asset" },
      { source: "account:brokerage:fubon", target: "position:fubon:2330", value: 420_000, tone: "asset" },
      { source: "account:crypto:maicoin", target: "position:maicoin:btc", value: 98_000, tone: "asset" },
    ],
  };
}
