import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source = readFileSync(new URL("./SnapshotSparkline.svelte", import.meta.url), "utf8");

assert.match(source, /x="position"/);
assert.match(source, /xValues = axisTimes\.map\(\(_, index\) => String\(index\)\)/);
assert.match(source, /xDomain = xValues;/);
assert.match(source, /tickSpacing: 80/);
assert.match(source, /transform=\{\{ mode: "domain", axis: "x" \}\}/);
assert.match(source, /tooltipContext=\{\{ mode: "band" \}\}/);
assert.match(source, /brush=\{\{ axis: "y", clickToReset: true, onBrushEnd: trackYRange \}\}/);
assert.match(source, /let brushedYDomain: \[number, number\] \| null = null;/);
assert.match(source, /function trackYRange\(\{ brush \}: \{ brush: \{ active\?: boolean; y: Array<number \| Date \| string \| null> \} \}\) \{/);
assert.match(source, /brushedYDomain = \[Math\.min\(start, end\), Math\.max\(start, end\)\];/);
assert.match(source, /brushedYDomain = null;/);
assert.match(source, /yDomain=\{brushedYDomain \?\? yDomain\}/);
assert.match(source, /function resetYRange\(\) \{/);
assert.match(source, /\{#if hasYRange\}/);
assert.match(source, /\{\$t\.spending\.chartReset\}/);
assert.match(source, /\{#key yRangeReset\}/);
assert.match(source, /rows !== lastRows \|\| currency !== lastCurrency \|\| amountKey !== lastAmountKey \|\| diverging !== lastDiverging/);
assert.doesNotMatch(source, /\bticks:/);
assert.match(source, /\.sparkline :global\(\.lc-layout-svg\)\s*\{[^}]*overflow:\s*hidden;/);
assert.match(source, /selectedSeriesKeys\.length === 1\s*\? buildTrendYAxis\(chartPoints\.map\(\(point\) => point\.value\)\)\s*:\s*buildCenteredSparklineYAxis\(chartPoints\.map\(\(point\) => point\.value\)\)/);
assert.match(source, /areaBaseline = selectedSeriesKeys\.length === 1\s*\? selectedSeriesKeys\[0\] === "liabilities" \? yAxis\.max : yAxis\.min\s*:\s*0/);
assert.match(source, /yBaseline=\{areaBaseline\}/);
assert.match(source, /fill-opacity:\s*0\.14;/);
assert.doesNotMatch(source, /\.snapshot-diverging-area\s*\{[^}]*opacity:\s*0;/);
assert.doesNotMatch(source, /\byTicks\b/);
assert.doesNotMatch(source, /snapshot-zero-break|snapshot-hidden-axis|zeroBreakAria/);
