import {
  CANONICAL_SCHEMA_VERSION,
  CATHAY_INTEGRATION_NAMESPACE,
  CATHAY_DOMESTIC_DEPOSIT_STREAM,
  CATHAY_DOMESTIC_DEPOSIT_AUTHORITY,
  CATHAY_DOMESTIC_DEPOSIT_CONTRACT_VERSION,
  CATHAY_DOMESTIC_DEPOSIT_TIME_ZONE,
  CATHAY_DERIVED_ORIGIN,
  FUBON_CREDIT_CARD_HUMAN_ATTESTED_V1,
  FUBON_CREDIT_CARD_HUMAN_ATTESTED_V2,
  ESUN_CREDIT_CARD_HUMAN_ATTESTED_V1,
  ESUN_CREDIT_CARD_HUMAN_ATTESTED_V2,
  YUANTA_CREDIT_CARD_HUMAN_ATTESTED_V1,
  YUANTA_CREDIT_CARD_HUMAN_ATTESTED_V2,
  FUBON_CREDIT_CARD_QUERY_ROUTES,
  ESUN_CREDIT_CARD_QUERY_ROUTES,
  YUANTA_CREDIT_CARD_QUERY_ROUTES,
  createCanonicalSchemaLifecyclePlan,
  SCHEMA_V15_INVESTMENTS,
  SCHEMA_V16_INVESTMENT_FUNDING_RELATIONS,
  isKnownRetiredFubonV18Fingerprint,
  isRetiredFubonV18RecoveryEligible,
  validateCanonicalInvestmentExtensionSchema,
  validateCanonicalInvestmentFundingRelationSchema,
  validateCanonicalLoanExtensionSchema,
  validateCanonicalLoanRepaymentRelationSchema,
  tableExists,
  relationType,
  columnExists,
  validateCanonicalContractPurgeSchema,
  validateCanonicalDatabaseAfterLifecycle,
  validateCanonicalSchemaMigrationMetadata,
  validateReadOnlyDatabase,
  validateV8SourceEvidenceSchema,
  validateCanonicalCompatibilityViews,
  validateCanonicalCaptureScopeLifecycleSchema,
  validateFinancialAccountCurrencyLifecycleSchema,
  validateCanonicalFinancialRevisionLifecycleSchema,
  validateCanonicalTimeObservationLifecycleSchema,
  validateCanonicalDepositoryBalanceSchema,
  validateForeignCurrencyConversionLifecycleSchema,
  ensureCanonicalEInvoiceSchema,
  validateCanonicalEInvoiceSchema,
  ensureCanonicalSpendingRecognitionSchema,
  validateCanonicalSpendingRecognitionSchema,
  hasCanonicalCreditCardExtension,
  hasFubonCreditCardExtension,
  canonicalCommitHasEvidence,
  validateGenerationExactAmounts,
  validateCanonicalAuthorityRoutes,
  recordProjectionGenerationEvent,
  validateGenerationTransactionIntegrity,
  validateGenerationFieldCompleteness,
  validateSelectedAssertionProvenance,
  validateGenerationFieldIntegrity,
  validateGenerationLifecycleCoordinates,
  validateUserAssertionProvenanceAuthority,
  validateProjectionGenerationProvenance,
  rejectStrayProjectionGenerations,
  projectionRelevantCommitCount,
  selectAssertionAsOf,
  validateCanonicalRelationResolutionCommitSchema,
  currentUtcMicros,
  quotedSqlIdentifier,
  isExactRetiredFubonV18BridgeState,
  SOURCE_CONNECTION_IDENTITY_V1_PURGE_ID,
  SOURCE_CONNECTION_IDENTITY_V1_PURGE_NAMESPACES,
  SOURCE_CONNECTION_IDENTITY_V1_PURGE_STREAMS,
  CREDIT_CARD_SOURCE_CONNECTION_V1_PURGE_ID,
  CREDIT_CARD_SOURCE_CONNECTION_V1_PURGE_NAMESPACES,
  CREDIT_CARD_SOURCE_CONNECTION_V1_PURGE_STREAMS,
  FUBON_DEPOSIT_OCCURRENCE_V1_PURGE_ID,
  FUBON_DEPOSIT_OCCURRENCE_V1_PURGE_NAMESPACES,
  FUBON_DEPOSIT_OCCURRENCE_V1_PURGE_STREAMS,
  YUANTA_TRADE_INVESTMENT_V2_PURGE_ID,
  YUANTA_TRADE_INVESTMENT_V2_PURGE_NAMESPACES,
  YUANTA_TRADE_INVESTMENT_V2_PURGE_STREAMS,
  YUANTA_TRADE_INVESTMENT_V3_PURGE_ID,
  YUANTA_TRADE_INVESTMENT_V3_PURGE_NAMESPACES,
  YUANTA_TRADE_INVESTMENT_V3_PURGE_STREAMS,
  type CanonicalDatabaseOptions,
} from "./canonical-schema-implementation.ts";
import {
  CanonicalSchemaLifecycle,
  type ValidatedCanonicalStore,
} from "./canonical-schema-lifecycle.ts";
import {
  applyCanonicalContractDataTransitions,
  validateRequiredCanonicalContractPurges,
} from "./canonical-contract-purge.ts";

/** Physical composition root. No production caller imports this module. */
export function composeCanonicalDatabase(
  path: string,
  options: CanonicalDatabaseOptions = {},
): ValidatedCanonicalStore {
  const validated = CanonicalSchemaLifecycle.open(
    path,
    createCanonicalSchemaLifecyclePlan(options),
    {
      readOnly: options.readOnly,
      busyTimeoutMs: options.runtime?.busyTimeoutMs ?? 30_000,
      maxAttempts: options.runtime?.maxAttempts,
      initialBackoffMs: options.runtime?.initialBackoffMs,
      maxBackoffMs: options.runtime?.maxBackoffMs,
    },
  );
  try {
    if (options.readOnly) {
      validateRequiredCanonicalContractPurges(validated.db);
    } else {
      validated.runContractPurgeDataTransition((db) =>
        applyCanonicalContractDataTransitions(db, validated.openedFromVersion),
      );
    }
    return validated;
  } catch (error) {
    validated.close();
    throw error;
  }
}

/**
 * Temporary internal operation table used while schema-specific validation is
 * progressively pulled behind deeper domain operations. Keeping it here
 * prevents the public database facade from importing the physical module.
 */
export const canonicalDatabasePhysicalOperations = Object.freeze({
  CANONICAL_SCHEMA_VERSION,
  CATHAY_INTEGRATION_NAMESPACE,
  CATHAY_DOMESTIC_DEPOSIT_STREAM,
  CATHAY_DOMESTIC_DEPOSIT_AUTHORITY,
  CATHAY_DOMESTIC_DEPOSIT_CONTRACT_VERSION,
  CATHAY_DOMESTIC_DEPOSIT_TIME_ZONE,
  CATHAY_DERIVED_ORIGIN,
  FUBON_CREDIT_CARD_HUMAN_ATTESTED_V1,
  FUBON_CREDIT_CARD_HUMAN_ATTESTED_V2,
  ESUN_CREDIT_CARD_HUMAN_ATTESTED_V1,
  ESUN_CREDIT_CARD_HUMAN_ATTESTED_V2,
  YUANTA_CREDIT_CARD_HUMAN_ATTESTED_V1,
  YUANTA_CREDIT_CARD_HUMAN_ATTESTED_V2,
  FUBON_CREDIT_CARD_QUERY_ROUTES,
  ESUN_CREDIT_CARD_QUERY_ROUTES,
  YUANTA_CREDIT_CARD_QUERY_ROUTES,
  SCHEMA_V15_INVESTMENTS,
  SCHEMA_V16_INVESTMENT_FUNDING_RELATIONS,
  createCanonicalSchemaLifecyclePlan,
  isKnownRetiredFubonV18Fingerprint,
  isRetiredFubonV18RecoveryEligible,
  validateCanonicalInvestmentExtensionSchema,
  validateCanonicalInvestmentFundingRelationSchema,
  validateCanonicalLoanExtensionSchema,
  validateCanonicalLoanRepaymentRelationSchema,
  tableExists,
  relationType,
  columnExists,
  validateCanonicalContractPurgeSchema,
  validateCanonicalDatabaseAfterLifecycle,
  validateCanonicalSchemaMigrationMetadata,
  validateReadOnlyDatabase,
  validateV8SourceEvidenceSchema,
  validateCanonicalCompatibilityViews,
  validateCanonicalCaptureScopeLifecycleSchema,
  validateFinancialAccountCurrencyLifecycleSchema,
  validateCanonicalFinancialRevisionLifecycleSchema,
  validateCanonicalTimeObservationLifecycleSchema,
  validateCanonicalDepositoryBalanceSchema,
  validateForeignCurrencyConversionLifecycleSchema,
  ensureCanonicalEInvoiceSchema,
  validateCanonicalEInvoiceSchema,
  ensureCanonicalSpendingRecognitionSchema,
  validateCanonicalSpendingRecognitionSchema,
  hasCanonicalCreditCardExtension,
  hasFubonCreditCardExtension,
  canonicalCommitHasEvidence,
  validateGenerationExactAmounts,
  validateCanonicalAuthorityRoutes,
  recordProjectionGenerationEvent,
  validateGenerationTransactionIntegrity,
  validateGenerationFieldCompleteness,
  validateSelectedAssertionProvenance,
  validateGenerationFieldIntegrity,
  validateGenerationLifecycleCoordinates,
  validateUserAssertionProvenanceAuthority,
  validateProjectionGenerationProvenance,
  rejectStrayProjectionGenerations,
  projectionRelevantCommitCount,
  selectAssertionAsOf,
  validateCanonicalRelationResolutionCommitSchema,
  currentUtcMicros,
  quotedSqlIdentifier,
  isExactRetiredFubonV18BridgeState,
  SOURCE_CONNECTION_IDENTITY_V1_PURGE_ID,
  SOURCE_CONNECTION_IDENTITY_V1_PURGE_NAMESPACES,
  SOURCE_CONNECTION_IDENTITY_V1_PURGE_STREAMS,
  CREDIT_CARD_SOURCE_CONNECTION_V1_PURGE_ID,
  CREDIT_CARD_SOURCE_CONNECTION_V1_PURGE_NAMESPACES,
  CREDIT_CARD_SOURCE_CONNECTION_V1_PURGE_STREAMS,
  FUBON_DEPOSIT_OCCURRENCE_V1_PURGE_ID,
  FUBON_DEPOSIT_OCCURRENCE_V1_PURGE_NAMESPACES,
  FUBON_DEPOSIT_OCCURRENCE_V1_PURGE_STREAMS,
  YUANTA_TRADE_INVESTMENT_V2_PURGE_ID,
  YUANTA_TRADE_INVESTMENT_V2_PURGE_NAMESPACES,
  YUANTA_TRADE_INVESTMENT_V2_PURGE_STREAMS,
  YUANTA_TRADE_INVESTMENT_V3_PURGE_ID,
  YUANTA_TRADE_INVESTMENT_V3_PURGE_NAMESPACES,
  YUANTA_TRADE_INVESTMENT_V3_PURGE_STREAMS,
});

export type { CanonicalDatabaseOptions };
