import type { LedgerQueryData } from "./accounts.ts";

type LedgerRow<K extends keyof LedgerQueryData> = LedgerQueryData[K][number];

const RUN_ID = "mock-run-2026-06-27";
const IMPORTED_AT = "2026-06-27T18:00:00.000Z";

export const MOCK_LEDGER_TABLES = [
  { key: "importRuns", table: "import_runs", label: "Import runs" },
  { key: "sourceFiles", table: "source_files", label: "Source files" },
  { key: "accountTransactions", table: "account_transactions", label: "TWD bank rows" },
  { key: "foreignCurrencyTransactions", table: "foreign_currency_transactions", label: "Foreign cash rows" },
  { key: "creditCardStatementLines", table: "credit_card_statement_lines", label: "Credit card rows" },
  { key: "loanTransactions", table: "loan_transactions", label: "Loan rows" },
  { key: "fundHoldings", table: "fund_holdings", label: "Fund positions" },
  { key: "fundBuyTransactions", table: "fund_buy_transactions", label: "Fund buys" },
  { key: "fundRedemptionTransactions", table: "fund_redemption_transactions", label: "Fund redemptions" },
  { key: "fundCashDividends", table: "fund_cash_dividends", label: "Fund dividends" },
  { key: "fundConversionTransactions", table: "fund_conversion_transactions", label: "Fund conversions" },
  { key: "brokerageHoldings", table: "brokerage_holdings", label: "Brokerage positions" },
  { key: "brokerageTradeTransactions", table: "brokerage_trade_transactions", label: "Brokerage trades" },
  { key: "maicoinAccountSnapshots", table: "maicoin_account_snapshots", label: "MaiCoin snapshots" },
  { key: "maicoinStatementRows", table: "maicoin_statement_rows", label: "MaiCoin statements" },
] as const satisfies ReadonlyArray<{
  key: keyof LedgerQueryData;
  table: string;
  label: string;
}>;

export function mockLedgerQueryData(): LedgerQueryData {
  return {
    importRuns,
    sourceFiles,
    accountTransactions,
    foreignCurrencyTransactions,
    creditCardStatementLines,
    loanTransactions,
    fundHoldings,
    fundBuyTransactions,
    fundRedemptionTransactions,
    fundCashDividends,
    fundConversionTransactions,
    brokerageHoldings,
    brokerageTradeTransactions,
    maicoinAccountSnapshots,
    maicoinStatementRows,
  };
}

function sourceFile(
  sourceFileId: string,
  bank: string,
  product: string,
  rowCount: number,
  modifiedDate: string,
): LedgerRow<"sourceFiles"> {
  return {
    sourceFileId,
    importRunId: RUN_ID,
    sourceFile: `downloads/mock/${sourceFileId}.csv`,
    sourceRelativePath: `mock/${sourceFileId}.csv`,
    sourceFileHash: `mock-file-hash-${sourceFileId}`,
    sourceFileBytes: rowCount * 256,
    sourceFileModifiedAt: `${modifiedDate}T09:00:00.000Z`,
    importedAt: IMPORTED_AT,
    bank,
    product,
    rowCount,
    status: "imported",
    recordJson: json({ mock: true, sourceFileId }),
  };
}

function common(sourceFileId: string, bank: string, product: string, sourceRowIndex: number) {
  const id = `${sourceFileId}.${sourceRowIndex}`;
  return {
    statementRowId: `mock-${id}`,
    sourceFileId,
    importRunId: RUN_ID,
    sourceRelativePath: `mock/${sourceFileId}.csv`,
    sourceRowIndex,
    sourceHash: `mock-source-${id}`,
    rawRowHash: `mock-raw-${id}`,
    contentHash: `mock-content-${id}`,
    bank,
    product,
    dedupeStatus: "unique",
    rawPayloadJson: json({ mock: true }),
    importedAt: IMPORTED_AT,
    createdAt: IMPORTED_AT,
  };
}

function json(value: Record<string, unknown>) {
  return JSON.stringify(value);
}

const importRuns: LedgerRow<"importRuns">[] = [
  {
    id: 1,
    importRunId: RUN_ID,
    startedAt: "2026-06-27T17:58:00.000Z",
    finishedAt: IMPORTED_AT,
    recordJson: json({
      schemaVersion: "mock-ledger.v1",
      importerName: "mock-dashboard",
      importedRows: 24,
    }),
  },
];

const sourceFiles: LedgerRow<"sourceFiles">[] = [
  sourceFile("account.2026-06-24", "fubon", "deposit", 1, "2026-06-24"),
  sourceFile("account.2026-06-27", "fubon", "deposit", 1, "2026-06-27"),
  sourceFile("foreign.2026-06-27", "cathay", "foreign-deposit", 2, "2026-06-27"),
  sourceFile("card.2026-06-27", "fubon", "credit-card", 3, "2026-06-27"),
  sourceFile("loan.2026-06-27", "yuanta", "mortgage", 1, "2026-06-27"),
  sourceFile("fund.2026-06-27", "yuanta", "fund", 5, "2026-06-27"),
  sourceFile("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 4, "2026-06-27"),
  sourceFile("unsupported.2026-06-27", "demo-bank", "unknown-export", 1, "2026-06-27"),
];

const accountTransactions: LedgerRow<"accountTransactions">[] = [
  {
    ...common("account.2026-06-24", "fubon", "deposit", 1),
    accountName: "Mock payroll account",
    accountNumber: "013245678900",
    currency: "TWD",
    accountingDate: "2026-06-24",
    transactionDate: "2026-06-24",
    transactionTime: "09:20:00",
    description: "Salary",
    withdrawalAmount: null,
    depositAmount: 3000,
    balanceAfter: 118000,
    note: null,
    fxRate: null,
  },
  {
    ...common("account.2026-06-27", "fubon", "deposit", 1),
    accountName: "Mock payroll account",
    accountNumber: "013245678900",
    currency: "TWD",
    accountingDate: "2026-06-27",
    transactionDate: "2026-06-27",
    transactionTime: "10:12:00",
    description: "Transfer in",
    withdrawalAmount: null,
    depositAmount: 7400,
    balanceAfter: 125400,
    note: "demo row",
    fxRate: null,
  },
];

const foreignCurrencyTransactions: LedgerRow<"foreignCurrencyTransactions">[] = [
  {
    ...common("foreign.2026-06-27", "cathay", "foreign-deposit", 1),
    accountName: "Mock foreign account",
    accountNumber: "9988776600",
    queryCurrency: "USD",
    currency: "USD",
    accountingDate: "2026-06-27",
    transactionDate: "2026-06-27",
    transactionTime: "11:00:00",
    description: "USD deposit",
    withdrawalAmount: null,
    depositAmount: 1200,
    balanceAfter: 8200,
    note: null,
    fxRate: 32.2,
  },
  {
    ...common("foreign.2026-06-27", "cathay", "foreign-deposit", 2),
    accountName: "Mock foreign account",
    accountNumber: "9988776600",
    queryCurrency: "JPY",
    currency: "JPY",
    accountingDate: "2026-06-27",
    transactionDate: "2026-06-27",
    transactionTime: "11:05:00",
    description: "JPY savings",
    withdrawalAmount: null,
    depositAmount: 50000,
    balanceAfter: 420000,
    note: null,
    fxRate: 0.22,
  },
];

const creditCardStatementLines: LedgerRow<"creditCardStatementLines">[] = [
  {
    ...common("card.2026-06-27", "fubon", "credit-card", 1),
    statementType: "unbilled",
    statementPeriod: "2026-06",
    cardNumber: "**** **** **** 1234",
    cardLabel: "Mock rewards card",
    consumeDate: "2026-06-25",
    postingDate: "2026-06-26",
    description: "Cloud subscription",
    countryCurrency: "TWD",
    foreignExchangeDate: null,
    foreignCurrency: null,
    foreignAmount: null,
    twdAmount: 1280,
    installmentAction: null,
    paymentStatus: "unpaid",
  },
  {
    ...common("card.2026-06-27", "fubon", "credit-card", 2),
    statementType: "unbilled",
    statementPeriod: "2026-06",
    cardNumber: "**** **** **** 1234",
    cardLabel: "Mock rewards card",
    consumeDate: "2026-06-27",
    postingDate: "2026-06-27",
    description: "Travel booking",
    countryCurrency: "USD",
    foreignExchangeDate: "2026-06-27",
    foreignCurrency: "USD",
    foreignAmount: 100,
    twdAmount: 3200,
    installmentAction: null,
    paymentStatus: "unpaid",
  },
  {
    ...common("card.2026-06-27", "fubon", "credit-card", 3),
    statementType: "billed",
    statementPeriod: "2026-05",
    cardNumber: "**** **** **** 1234",
    cardLabel: "Mock rewards card",
    consumeDate: "2026-05-30",
    postingDate: "2026-05-31",
    description: "Paid statement item",
    countryCurrency: "TWD",
    foreignExchangeDate: null,
    foreignCurrency: null,
    foreignAmount: null,
    twdAmount: 860,
    installmentAction: null,
    paymentStatus: "paid",
  },
];

const loanTransactions: LedgerRow<"loanTransactions">[] = [
  {
    ...common("loan.2026-06-27", "yuanta", "mortgage", 1),
    accountNumber: "LN-2026-0001",
    tradeDate: "2026-06-27",
    postingDate: "2026-06-27",
    item: "Monthly repayment",
    interestStartDate: "2026-05-27",
    interestEndDate: "2026-06-26",
    amount: 18800,
    interestRate: "2.18%",
    balanceAfter: 3180000,
    overpayment: 0,
    note: "principal + interest",
  },
];

const fundHoldings: LedgerRow<"fundHoldings">[] = [
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 1),
    dataType: "holding",
    fundId: "FUND-TWD-001",
    queryPeriod: "2026-06",
    fundName: "Mock Taiwan Equity Fund",
    fundType: "equity",
    currency: "TWD",
    investmentAmount: 240000,
    marketValueWithoutDividend: 280000,
    unrealizedPnlWithoutDividend: 40000,
    returnRateWithoutDividend: "16.67",
    unrealizedPnlWithDividend: 45500,
    returnRateWithDividend: "18.96",
    holdingStatus: "active",
  },
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 2),
    dataType: "holding",
    fundId: "FUND-USD-002",
    queryPeriod: "2026-06",
    fundName: "Mock Global Bond Fund",
    fundType: "bond",
    currency: "USD",
    investmentAmount: 12000,
    marketValueWithoutDividend: 12800,
    unrealizedPnlWithoutDividend: 800,
    returnRateWithoutDividend: "6.67",
    unrealizedPnlWithDividend: 950,
    returnRateWithDividend: "7.92",
    holdingStatus: "active",
  },
];

const fundBuyTransactions: LedgerRow<"fundBuyTransactions">[] = [
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 3),
    fundId: "FUND-TWD-001",
    investmentDate: "2026-06-20",
    fundName: "Mock Taiwan Equity Fund",
    transactionNumber: "FB-001",
    currency: "TWD",
    investmentAmount: 30000,
    subscriptionFee: 150,
    subscriptionFeeCurrency: "TWD",
    subscribedUnits: 1520.4,
  },
];

const fundRedemptionTransactions: LedgerRow<"fundRedemptionTransactions">[] = [
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 4),
    fundId: "FUND-TWD-001",
    redemptionDate: "2026-06-21",
    fundName: "Mock Taiwan Equity Fund",
    transactionNumber: "FR-001",
    redemptionInvestmentAmount: 12000,
    redemptionUnits: 600.2,
    netDepositAmount: 13500,
    referencePnl: 1500,
    note: "partial redemption",
  },
];

const fundCashDividends: LedgerRow<"fundCashDividends">[] = [
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 5),
    fundId: "FUND-USD-002",
    depositDate: "2026-06-26",
    fundName: "Mock Global Bond Fund",
    transactionNumber: "FD-001",
    currency: "USD",
    distributionAmount: 82,
    distributionCurrency: "USD",
    fxRate: 32.1,
  },
];

const fundConversionTransactions: LedgerRow<"fundConversionTransactions">[] = [
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 6),
    queryPeriod: "2026-06",
    conversionOutDate: "2026-06-18",
    conversionInDate: "2026-06-19",
    transactionNumber: "FC-001",
    fromFundName: "Mock Balanced Fund",
    toFundName: "Mock Taiwan Equity Fund",
    conversionInvestmentAmount: 50000,
  },
];

const brokerageHoldings: LedgerRow<"brokerageHoldings">[] = [
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 1),
    asOfDate: "2026-06-27",
    accountNumber: "BR-0001",
    assetType: "stock",
    subCategory: "listed",
    productCode: "2330",
    productName: "Mock Semiconductor",
    currency: "TWD",
    quantity: 200,
    marketDate: "2026-06-27",
    marketPrice: 980,
    marketValueOriginal: 196000,
    marketValueTwd: 196000,
    costPrice: 760,
    costAmount: 152000,
    unrealizedPnlOriginal: 44000,
    unrealizedPnlTwd: 44000,
    returnRate: "28.95",
    fxRate: 1,
  },
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 2),
    asOfDate: "2026-06-27",
    accountNumber: "BR-0001",
    assetType: "etf",
    subCategory: "overseas",
    productCode: "VT",
    productName: "Mock World ETF",
    currency: "USD",
    quantity: 80,
    marketDate: "2026-06-27",
    marketPrice: 118.4,
    marketValueOriginal: 9472,
    marketValueTwd: 305000,
    costPrice: 105,
    costAmount: 8400,
    unrealizedPnlOriginal: 1072,
    unrealizedPnlTwd: 34500,
    returnRate: "12.76",
    fxRate: 32.2,
  },
];

const brokerageTradeTransactions: LedgerRow<"brokerageTradeTransactions">[] = [
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 3),
    tradeDate: "2026-06-17",
    accountNumber: "BR-0001",
    assetType: "stock",
    tradeType: "regular",
    subCategory: "listed",
    productCode: "2330",
    productName: "Mock Semiconductor",
    currency: "TWD",
    action: "buy",
    quantity: 100,
    price: 960,
    grossAmount: -96000,
    fee: 137,
    tax: 0,
    settlementAmount: -96137,
    settlementCurrency: "TWD",
    realizedPnl: null,
    costAmount: 96000,
  },
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 4),
    tradeDate: "2026-06-24",
    accountNumber: "BR-0001",
    assetType: "etf",
    tradeType: "regular",
    subCategory: "overseas",
    productCode: "VT",
    productName: "Mock World ETF",
    currency: "USD",
    action: "buy",
    quantity: 20,
    price: 116,
    grossAmount: -2320,
    fee: 4.99,
    tax: 0,
    settlementAmount: -2324.99,
    settlementCurrency: "USD",
    realizedPnl: null,
    costAmount: 2320,
  },
];

const maicoinAccountSnapshots: LedgerRow<"maicoinAccountSnapshots">[] = [
  {
    snapshotId: "mock-btc-snapshot",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    subAccount: "main",
    walletType: "spot",
    currency: "BTC",
    balance: 0.2,
    locked: 0,
    staked: null,
    principal: null,
    interest: null,
    totalQuantity: 0.2,
    priceMarket: "btctwd",
    priceCurrency: "TWD",
    price: 2100000,
    valueTwd: 420000,
    priceAt: "2026-06-27T11:59:00.000Z",
    rawAccountJson: json({ mock: true, currency: "BTC" }),
    rawPriceJson: json({ market: "btctwd", price: 2100000 }),
    createdAt: IMPORTED_AT,
  },
  {
    snapshotId: "mock-usdt-debt-snapshot",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    subAccount: "main",
    walletType: "m",
    currency: "USDT",
    balance: 0,
    locked: 0,
    staked: null,
    principal: 1200,
    interest: 18,
    totalQuantity: 0,
    priceMarket: "usdttwd",
    priceCurrency: "TWD",
    price: 31.8,
    valueTwd: null,
    priceAt: "2026-06-27T11:59:00.000Z",
    rawAccountJson: json({ mock: true, currency: "USDT" }),
    rawPriceJson: json({ market: "usdttwd", price: 31.8 }),
    createdAt: IMPORTED_AT,
  },
];

const maicoinStatementRows: LedgerRow<"maicoinStatementRows">[] = [
  {
    statementId: "mock-max-trade-btc",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    endpoint: "/api/v2/members/me/trades",
    walletType: "spot",
    rowType: "trade",
    externalId: "mock-trade-1",
    occurredAt: "2026-06-12T10:30:00.000Z",
    currency: "BTC",
    amount: 0.18,
    fee: 45,
    feeCurrency: "TWD",
    market: "btctwd",
    side: "bid",
    price: 1833333,
    valueTwd: 330000,
    rawPayloadJson: json({
      market: "btctwd",
      side: "bid",
      volume: 0.18,
      funds: 330000,
      fee_currency: "TWD",
      fee: 45,
    }),
    createdAt: IMPORTED_AT,
    updatedAt: IMPORTED_AT,
  },
  {
    statementId: "mock-max-deposit-btc",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    endpoint: "/api/v2/deposit",
    walletType: "spot",
    rowType: "deposit",
    externalId: "mock-deposit-1",
    occurredAt: "2026-06-20T10:30:00.000Z",
    currency: "BTC",
    amount: 0.02,
    fee: null,
    feeCurrency: null,
    market: null,
    side: null,
    price: null,
    valueTwd: 48000,
    rawPayloadJson: json({ currency: "BTC", amount: 0.02, state: "accepted" }),
    createdAt: IMPORTED_AT,
    updatedAt: IMPORTED_AT,
  },
  {
    statementId: "mock-max-reward-btc",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    endpoint: "/api/v2/rewards",
    walletType: "spot",
    rowType: "reward",
    externalId: "mock-reward-1",
    occurredAt: "2026-06-26T10:30:00.000Z",
    currency: "BTC",
    amount: 0.001,
    fee: null,
    feeCurrency: null,
    market: null,
    side: null,
    price: null,
    valueTwd: 2100,
    rawPayloadJson: json({ currency: "BTC", amount: 0.001, note: "staking reward" }),
    createdAt: IMPORTED_AT,
    updatedAt: IMPORTED_AT,
  },
];
