import type { LedgerQueryData } from "./accounts.ts";

type LedgerRow<K extends keyof LedgerQueryData> = LedgerQueryData[K][number];

const RUN_ID = "mock-run-2026-06-27";
const IMPORTED_AT = "2026-06-27T18:00:00.000Z";

export const MOCK_LEDGER_TABLES = [
  { key: "importRuns", table: "import_runs", label: "Import runs" },
  { key: "sourceFiles", table: "source_files", label: "Source files" },
  { key: "accountTransactions", table: "account_transactions", label: "TWD bank rows" },
  { key: "foreignCurrencyTransactions", table: "foreign_currency_transactions", label: "Foreign cash rows" },
  { key: "creditCardStatementLines", table: "credit_card_statement_lines", label: "Credit card rows" },
  { key: "creditCardCaptures", table: "credit_card_captures", label: "Credit card captures" },
  { key: "creditCardCaptureEntries", table: "credit_card_capture_entries", label: "Credit card capture entries" },
  { key: "creditCardSnapshots", table: "credit_card_snapshots", label: "Credit card snapshots" },
  { key: "loanTransactions", table: "loan_transactions", label: "Loan rows" },
  { key: "fundHoldings", table: "fund_holdings", label: "Fund positions" },
  { key: "fundBuyTransactions", table: "fund_buy_transactions", label: "Fund buys" },
  { key: "fundRedemptionTransactions", table: "fund_redemption_transactions", label: "Fund redemptions" },
  { key: "fundCashDividends", table: "fund_cash_dividends", label: "Fund dividends" },
  { key: "fundConversionTransactions", table: "fund_conversion_transactions", label: "Fund conversions" },
  { key: "brokerageHoldings", table: "brokerage_holdings", label: "Brokerage positions" },
  { key: "brokerageTradeTransactions", table: "brokerage_trade_transactions", label: "Brokerage trades" },
  { key: "maicoinAccountSnapshots", table: "maicoin_account_snapshots", label: "MaiCoin snapshots" },
  { key: "maicoinStatementRows", table: "maicoin_statement_rows", label: "MaiCoin statements" },
] as const satisfies ReadonlyArray<{
  key: keyof LedgerQueryData;
  table: string;
  label: string;
}>;

export function mockLedgerQueryData(referenceDate = new Date()): LedgerQueryData {
  return shiftTemplateDates({
    importRuns,
    sourceFiles,
    accountTransactions,
    foreignCurrencyTransactions,
    creditCardStatementLines,
    creditCardCaptures,
    creditCardCaptureEntries,
    creditCardSnapshots,
    loanTransactions,
    fundHoldings,
    fundBuyTransactions,
    fundRedemptionTransactions,
    fundCashDividends,
    fundConversionTransactions,
    brokerageHoldings,
    brokerageTradeTransactions,
    maicoinAccountSnapshots,
    maicoinStatementRows,
  }, referenceDate);
}

const TEMPLATE_LATEST_DATE = Date.UTC(2026, 5, 28);

function shiftTemplateDates(data: LedgerQueryData, referenceDate: Date): LedgerQueryData {
  const launch = taipeiCalendarDate(referenceDate);
  const dayOffset = Math.round((launch - TEMPLATE_LATEST_DATE) / 86_400_000);
  const monthOffset = new Date(launch).getUTCFullYear() * 12 + new Date(launch).getUTCMonth()
    - (2026 * 12 + 5);

  return shiftValue(data, dayOffset, monthOffset) as LedgerQueryData;
}

function taipeiCalendarDate(value: Date): number {
  const parts = new Intl.DateTimeFormat("en", {
    day: "numeric",
    month: "numeric",
    year: "numeric",
    timeZone: "Asia/Taipei",
  }).formatToParts(value);
  const number = (type: Intl.DateTimeFormatPartTypes) =>
    Number(parts.find((part) => part.type === type)?.value);
  return Date.UTC(number("year"), number("month") - 1, number("day"));
}

function shiftValue(value: unknown, dayOffset: number, monthOffset: number): unknown {
  if (Array.isArray(value)) return value.map((item) => shiftValue(item, dayOffset, monthOffset));
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, shiftValue(item, dayOffset, monthOffset)]),
    );
  }
  if (typeof value !== "string") return value;
  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return shiftDate(value, dayOffset);
  if (/^\d{4}-\d{2}-\d{2}T/.test(value)) {
    const shiftedDate = shiftDate(value.slice(0, 10), dayOffset);
    return `${shiftedDate}${value.slice(10)}`;
  }
  if (/^\d{4}-\d{2}$/.test(value)) {
    const [year, month] = value.split("-").map(Number);
    const shifted = new Date(Date.UTC(year, month - 1 + monthOffset, 1));
    return `${shifted.getUTCFullYear()}-${String(shifted.getUTCMonth() + 1).padStart(2, "0")}`;
  }
  return value;
}

function shiftDate(value: string, dayOffset: number): string {
  const [year, month, day] = value.split("-").map(Number);
  return new Date(Date.UTC(year, month - 1, day + dayOffset)).toISOString().slice(0, 10);
}

function sourceFile(
  sourceFileId: string,
  bank: string,
  product: string,
  rowCount: number,
  modifiedDate: string,
): LedgerRow<"sourceFiles"> {
  return {
    sourceFileId,
    importRunId: RUN_ID,
    sourceFile: `downloads/mock/${sourceFileId}.csv`,
    sourceRelativePath: `mock/${sourceFileId}.csv`,
    sourceFileHash: `mock-file-hash-${sourceFileId}`,
    sourceFileBytes: rowCount * 256,
    sourceFileModifiedAt: `${modifiedDate}T09:00:00.000Z`,
    importedAt: IMPORTED_AT,
    bank,
    product,
    rowCount,
    status: "imported",
    recordJson: json({ mock: true, sourceFileId }),
  };
}

function common(sourceFileId: string, bank: string, product: string, sourceRowIndex: number) {
  const id = `${sourceFileId}.${sourceRowIndex}`;
  return {
    statementRowId: `mock-${id}`,
    sourceFileId,
    importRunId: RUN_ID,
    sourceRelativePath: `mock/${sourceFileId}.csv`,
    sourceRowIndex,
    sourceHash: `mock-source-${id}`,
    contentHash: `mock-content-${id}`,
    bank,
    product,
    rawPayloadJson: json({ mock: true }),
    importedAt: IMPORTED_AT,
    createdAt: IMPORTED_AT,
  };
}

function creditCardCommon(
  sourceFileId: string,
  bank: string,
  product: string,
  sourceRowIndex: number,
) {
  return {
    ...common(sourceFileId, bank, product, sourceRowIndex),
    contentKey: null,
    occurrenceIndex: null,
    firstSeenAt: null,
    lastSeenAt: null,
  };
}

function json(value: Record<string, unknown>) {
  return JSON.stringify(value);
}

const importRuns: LedgerRow<"importRuns">[] = [
  {
    id: 1,
    importRunId: RUN_ID,
    startedAt: "2026-06-27T17:58:00.000Z",
    finishedAt: IMPORTED_AT,
    recordJson: json({
      schemaVersion: "mock-ledger.v1",
      importerName: "mock-dashboard",
      importedRows: 47,
    }),
  },
];

const sourceFiles: LedgerRow<"sourceFiles">[] = [
  sourceFile("account.2026-06-24", "fubon", "deposit", 1, "2026-06-24"),
  sourceFile("account.2026-06-27", "fubon", "deposit", 5, "2026-06-27"),
  sourceFile("foreign.2026-06-27", "cathay", "foreign-deposit", 5, "2026-06-25"),
  sourceFile("card.2026-05-22", "fubon", "credit-card", 3, "2026-05-22"),
  sourceFile("card.2026-06-24", "fubon", "credit-card", 1, "2026-06-24"),
  sourceFile("card.2026-06-25", "fubon", "credit-card", 1, "2026-06-25"),
  sourceFile("card.2026-06-26", "fubon", "credit-card", 1, "2026-06-26"),
  sourceFile("card.2026-06-27", "fubon", "credit-card", 2, "2026-06-27"),
  sourceFile("loan.2026-06-26", "yuanta", "mortgage", 1, "2026-06-26"),
  sourceFile("loan.2026-06-27", "yuanta", "mortgage", 1, "2026-06-27"),
  sourceFile("loan.2026-06-28", "yuanta", "mortgage", 1, "2026-06-28"),
  sourceFile("fund.2026-06-27", "yuanta", "fund", 13, "2026-06-23"),
  sourceFile("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 11, "2026-06-26"),
  sourceFile("unsupported.2026-06-27", "demo-bank", "unknown-export", 1, "2026-06-27"),
];

const accountTransactions: LedgerRow<"accountTransactions">[] = [
  {
    ...common("account.2026-06-24", "fubon", "deposit", 1),
    accountName: "富邦薪轉帳戶",
    accountNumber: "MOCK-PAYROLL",
    currency: "TWD",
    accountingDate: "2026-06-24",
    transactionDate: "2026-06-24",
    transactionTime: "09:20:00",
    description: "薪資入帳",
    withdrawalAmount: null,
    depositAmount: 88000,
    balanceAfter: 153000,
    note: null,
    fxRate: null,
  },
  {
    ...common("account.2026-06-27", "fubon", "deposit", 1),
    accountName: "富邦薪轉帳戶",
    accountNumber: "MOCK-PAYROLL",
    currency: "TWD",
    accountingDate: "2026-06-27",
    transactionDate: "2026-06-27",
    transactionTime: "10:12:00",
    description: "費用分攤轉入",
    withdrawalAmount: null,
    depositAmount: 7400,
    balanceAfter: 125980,
    note: "demo row",
    fxRate: null,
  },
  {
    ...common("account.2026-06-27", "fubon", "deposit", 2),
    accountName: "富邦薪轉帳戶",
    accountNumber: "MOCK-PAYROLL",
    currency: "TWD",
    accountingDate: "2026-06-25",
    transactionDate: "2026-06-25",
    transactionTime: "12:40:00",
    description: "房租轉帳",
    withdrawalAmount: 28000,
    depositAmount: null,
    balanceAfter: 125000,
    note: "monthly housing",
    fxRate: null,
  },
  {
    ...common("account.2026-06-27", "fubon", "deposit", 3),
    accountName: "富邦薪轉帳戶",
    accountNumber: "MOCK-PAYROLL",
    currency: "TWD",
    accountingDate: "2026-06-26",
    transactionDate: "2026-06-26",
    transactionTime: "14:15:00",
    description: "信用卡自動扣繳",
    withdrawalAmount: 6420,
    depositAmount: null,
    balanceAfter: 118580,
    note: "June card bill",
    fxRate: null,
  },
  {
    ...common("account.2026-06-27", "fubon", "deposit", 4),
    accountName: "富邦數位備用金",
    accountNumber: "MOCK-EMERGENCY",
    currency: "TWD",
    accountingDate: "2026-06-27",
    transactionDate: "2026-06-27",
    transactionTime: "15:30:00",
    description: "每月儲蓄",
    withdrawalAmount: null,
    depositAmount: 20000,
    balanceAfter: 420000,
    note: null,
    fxRate: null,
  },
  {
    ...common("account.2026-06-27", "fubon", "deposit", 5),
    accountName: "富邦數位備用金",
    accountNumber: "MOCK-EMERGENCY",
    currency: "TWD",
    accountingDate: "2026-06-27",
    transactionDate: "2026-06-27",
    transactionTime: "16:05:00",
    description: "ATM 提款",
    withdrawalAmount: 3000,
    depositAmount: null,
    balanceAfter: 417000,
    note: "cash buffer",
    fxRate: null,
  },
];

const foreignCurrencyTransactions: LedgerRow<"foreignCurrencyTransactions">[] = [
  {
    ...common("foreign.2026-06-27", "cathay", "foreign-deposit", 1),
    accountName: "國泰外幣帳戶",
    accountNumber: "MOCK-FX-MAIN",
    queryCurrency: "USD",
    currency: "USD",
    accountingDate: "2026-06-27",
    transactionDate: "2026-06-27",
    transactionTime: "11:00:00",
    description: "美元定期換匯",
    withdrawalAmount: null,
    depositAmount: 1200,
    balanceAfter: 8200,
    note: null,
    fxRate: 32.2,
  },
  {
    ...common("foreign.2026-06-27", "cathay", "foreign-deposit", 2),
    accountName: "國泰外幣帳戶",
    accountNumber: "MOCK-FX-MAIN",
    queryCurrency: "JPY",
    currency: "JPY",
    accountingDate: "2026-06-25",
    transactionDate: "2026-06-25",
    transactionTime: "11:05:00",
    description: "日圓旅遊準備金",
    withdrawalAmount: null,
    depositAmount: 50000,
    balanceAfter: 420000,
    note: null,
    fxRate: 0.22,
  },
  {
    ...common("foreign.2026-06-27", "cathay", "foreign-deposit", 3),
    accountName: "國泰外幣帳戶",
    accountNumber: "MOCK-FX-MAIN",
    queryCurrency: "USD",
    currency: "USD",
    accountingDate: "2026-06-26",
    transactionDate: "2026-06-26",
    transactionTime: "13:25:00",
    description: "美元匯款手續費",
    withdrawalAmount: 15,
    depositAmount: null,
    balanceAfter: 8185,
    note: "outbound fee",
    fxRate: 32.2,
  },
  {
    ...common("foreign.2026-06-27", "cathay", "foreign-deposit", 4),
    accountName: "玉山旅遊外幣帳戶",
    accountNumber: "MOCK-FX-TRAVEL",
    queryCurrency: "EUR",
    currency: "EUR",
    accountingDate: "2026-06-24",
    transactionDate: "2026-06-24",
    transactionTime: "13:50:00",
    description: "歐元換匯",
    withdrawalAmount: null,
    depositAmount: 600,
    balanceAfter: 2600,
    note: null,
    fxRate: 34.8,
  },
  {
    ...common("foreign.2026-06-27", "cathay", "foreign-deposit", 5),
    accountName: "玉山旅遊外幣帳戶",
    accountNumber: "MOCK-FX-TRAVEL",
    queryCurrency: "HKD",
    currency: "HKD",
    accountingDate: "2026-06-26",
    transactionDate: "2026-06-26",
    transactionTime: "14:10:00",
    description: "港幣換匯",
    withdrawalAmount: null,
    depositAmount: 8800,
    balanceAfter: 18800,
    note: null,
    fxRate: 4.1,
  },
];

const creditCardStatementLines: LedgerRow<"creditCardStatementLines">[] = [
  {
    ...creditCardCommon("card.2026-06-25", "fubon", "credit-card", 1),
    semanticKey: null,
    statementType: "unbilled",
    statementPeriod: "2026-06",
    cardNumber: "**** **** **** 1234",
    cardLabel: "富邦 Costco 卡",
    consumeDate: "2026-06-25",
    postingDate: "2026-06-26",
    description: "雲端服務訂閱",
    countryCurrency: "TWD",
    foreignExchangeDate: null,
    foreignCurrency: null,
    foreignAmount: null,
    twdAmount: 1280,
    installmentAction: null,
    paymentStatus: "unpaid",
  },
  {
    ...creditCardCommon("card.2026-06-27", "fubon", "credit-card", 2),
    semanticKey: null,
    statementType: "unbilled",
    statementPeriod: "2026-06",
    cardNumber: "**** **** **** 1234",
    cardLabel: "富邦 Costco 卡",
    consumeDate: "2026-06-27",
    postingDate: "2026-06-27",
    description: "高鐵假期訂房",
    countryCurrency: "USD",
    foreignExchangeDate: "2026-06-27",
    foreignCurrency: "USD",
    foreignAmount: 100,
    twdAmount: 3200,
    installmentAction: null,
    paymentStatus: "unpaid",
  },
  {
    ...creditCardCommon("card.2026-05-22", "fubon", "credit-card", 3),
    semanticKey: null,
    statementType: "billed",
    statementPeriod: "2026-05",
    cardNumber: "**** **** **** 1234",
    cardLabel: "富邦 Costco 卡",
    consumeDate: "2026-05-30",
    postingDate: "2026-05-31",
    description: "上期餐飲消費",
    countryCurrency: "TWD",
    foreignExchangeDate: null,
    foreignCurrency: null,
    foreignAmount: null,
    twdAmount: 860,
    installmentAction: null,
    paymentStatus: "paid",
  },
  {
    ...creditCardCommon("card.2026-06-27", "fubon", "credit-card", 4),
    semanticKey: null,
    statementType: "unbilled",
    statementPeriod: "2026-06",
    cardNumber: "**** **** **** 1234",
    cardLabel: "富邦 Costco 卡",
    consumeDate: "2026-06-27",
    postingDate: "2026-06-28",
    description: "全聯福利中心",
    countryCurrency: "TWD",
    foreignExchangeDate: null,
    foreignCurrency: null,
    foreignAmount: null,
    twdAmount: 2380,
    installmentAction: null,
    paymentStatus: "unpaid",
  },
  {
    ...creditCardCommon("card.2026-06-26", "fubon", "credit-card", 5),
    semanticKey: null,
    statementType: "unbilled",
    statementPeriod: "2026-06",
    cardNumber: "**** **** **** 5678",
    cardLabel: "富邦 J 卡",
    consumeDate: "2026-06-26",
    postingDate: "2026-06-27",
    description: "東京飯店訂金",
    countryCurrency: "JPY",
    foreignExchangeDate: "2026-06-27",
    foreignCurrency: "JPY",
    foreignAmount: 22000,
    twdAmount: 4840,
    installmentAction: null,
    paymentStatus: "unpaid",
  },
  {
    ...creditCardCommon("card.2026-06-24", "fubon", "credit-card", 6),
    semanticKey: null,
    statementType: "unbilled",
    statementPeriod: "2026-06",
    cardNumber: "**** **** **** 5678",
    cardLabel: "富邦 J 卡",
    consumeDate: "2026-06-24",
    postingDate: "2026-06-25",
    description: "洗衣機分期",
    countryCurrency: "TWD",
    foreignExchangeDate: null,
    foreignCurrency: null,
    foreignAmount: null,
    twdAmount: 3900,
    installmentAction: "installment 1/6",
    paymentStatus: "unpaid",
  },
  {
    ...creditCardCommon("card.2026-05-22", "fubon", "credit-card", 7),
    semanticKey: null,
    statementType: "billed",
    statementPeriod: "2026-05",
    cardNumber: "**** **** **** 5678",
    cardLabel: "富邦 J 卡",
    consumeDate: "2026-05-18",
    postingDate: "2026-05-19",
    description: "日本航空機票",
    countryCurrency: "USD",
    foreignExchangeDate: "2026-05-19",
    foreignCurrency: "USD",
    foreignAmount: 240,
    twdAmount: 7728,
    installmentAction: null,
    paymentStatus: "paid",
  },
  {
    ...creditCardCommon("card.2026-05-22", "fubon", "credit-card", 8),
    semanticKey: null,
    statementType: "billed",
    statementPeriod: "2026-05",
    cardNumber: "**** **** **** 1234",
    cardLabel: "富邦 Costco 卡",
    consumeDate: "2026-05-21",
    postingDate: "2026-05-22",
    description: "網購退貨退款",
    countryCurrency: "TWD",
    foreignExchangeDate: null,
    foreignCurrency: null,
    foreignAmount: null,
    twdAmount: -420,
    installmentAction: null,
    paymentStatus: "paid",
  },
];

const creditCardCaptures: LedgerRow<"creditCardCaptures">[] = [];
const creditCardCaptureEntries: LedgerRow<"creditCardCaptureEntries">[] = [];

const creditCardSnapshots: LedgerRow<"creditCardSnapshots">[] = [
  cardSnapshot("card.2026-05-22", "1234", "billed", "2026-05-22", 440, 2),
  cardSnapshot("card.2026-05-22", "5678", "billed", "2026-05-22", 7728, 1),
  cardSnapshot("card.2026-06-24", "5678", "unbilled", "2026-06-24", 3900, 1),
  cardSnapshot("card.2026-06-25", "1234", "unbilled", "2026-06-25", 1280, 1),
  cardSnapshot("card.2026-06-26", "5678", "unbilled", "2026-06-26", 4840, 1),
  cardSnapshot("card.2026-06-27", "1234", "unbilled", "2026-06-27", 5580, 2),
];

function cardSnapshot(
  sourceFileId: string,
  cardKey: string,
  statementType: "billed" | "unbilled",
  asOfDate: string,
  totalAmount: number,
  transactionCount: number,
): LedgerRow<"creditCardSnapshots"> {
  return {
    snapshotId: `mock-snapshot-${sourceFileId}-${cardKey}-${statementType}`,
    captureId: null,
    sourceFileId,
    bank: "fubon",
    product: "credit-card",
    cardKey,
    statementType,
    capturedAt: `${asOfDate}T18:00:00.000Z`,
    asOfDate,
    currency: "TWD",
    transactionCount,
    totalAmount,
  };
}

const loanTransactions: LedgerRow<"loanTransactions">[] = [
  {
    ...common("loan.2026-06-27", "yuanta", "mortgage", 1),
    accountNumber: "LN-2026-0001",
    tradeDate: "2026-06-27",
    postingDate: "2026-06-27",
    item: "Monthly repayment",
    interestStartDate: "2026-05-27",
    interestEndDate: "2026-06-26",
    amount: 18800,
    interestRate: "2.18%",
    balanceAfter: 3180000,
    overpayment: 0,
    note: "principal + interest",
  },
  {
    ...common("loan.2026-06-28", "yuanta", "mortgage", 2),
    accountNumber: "LN-2026-0001",
    tradeDate: "2026-06-28",
    postingDate: "2026-06-28",
    item: "Principal prepayment",
    interestStartDate: null,
    interestEndDate: null,
    amount: 50000,
    interestRate: "2.18%",
    balanceAfter: 3130000,
    overpayment: 50000,
    note: "extra principal",
  },
  {
    ...common("loan.2026-06-26", "yuanta", "mortgage", 3),
    accountNumber: "LN-2026-0002",
    tradeDate: "2026-06-26",
    postingDate: "2026-06-26",
    item: "Car loan repayment",
    interestStartDate: "2026-05-27",
    interestEndDate: "2026-06-26",
    amount: 9200,
    interestRate: "2.65%",
    balanceAfter: 428000,
    overpayment: 0,
    note: "secondary loan",
  },
];

const fundHoldings: LedgerRow<"fundHoldings">[] = [
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 1),
    dataType: "holding",
    fundId: "FUND-TWD-001",
    queryPeriod: "2026-06",
    fundName: "元大台灣卓越基金",
    fundType: "equity",
    currency: "TWD",
    investmentAmount: 240000,
    marketValueWithoutDividend: 280000,
    unrealizedPnlWithoutDividend: 40000,
    returnRateWithoutDividend: "16.67",
    unrealizedPnlWithDividend: 45500,
    returnRateWithDividend: "18.96",
    holdingStatus: "active",
  },
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 2),
    dataType: "holding",
    fundId: "FUND-USD-002",
    queryPeriod: "2026-05",
    fundName: "全球投資級債券基金",
    fundType: "bond",
    currency: "USD",
    investmentAmount: 12000,
    marketValueWithoutDividend: 12800,
    unrealizedPnlWithoutDividend: 800,
    returnRateWithoutDividend: "6.67",
    unrealizedPnlWithDividend: 950,
    returnRateWithDividend: "7.92",
    holdingStatus: "active",
  },
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 7),
    dataType: "holding",
    fundId: "FUND-TWD-003",
    queryPeriod: "2026-06",
    fundName: "台灣科技成長基金",
    fundType: "sector",
    currency: "TWD",
    investmentAmount: 160000,
    marketValueWithoutDividend: 144000,
    unrealizedPnlWithoutDividend: -16000,
    returnRateWithoutDividend: "-10.00",
    unrealizedPnlWithDividend: -15200,
    returnRateWithDividend: "-9.50",
    holdingStatus: "active",
  },
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 8),
    dataType: "holding",
    fundId: "FUND-JPY-004",
    queryPeriod: "2026-05",
    fundName: "日本不動產收益基金",
    fundType: "reit",
    currency: "JPY",
    investmentAmount: 900000,
    marketValueWithoutDividend: 945000,
    unrealizedPnlWithoutDividend: 45000,
    returnRateWithoutDividend: "5.00",
    unrealizedPnlWithDividend: 49200,
    returnRateWithDividend: "5.47",
    holdingStatus: "active",
  },
];

const fundBuyTransactions: LedgerRow<"fundBuyTransactions">[] = [
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 3),
    fundId: "FUND-TWD-001",
    investmentDate: "2026-06-20",
    fundName: "元大台灣卓越基金",
    transactionNumber: "FB-001",
    currency: "TWD",
    investmentAmount: 30000,
    subscriptionFee: 150,
    subscriptionFeeCurrency: "TWD",
    subscribedUnits: 1520.4,
  },
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 9),
    fundId: "FUND-TWD-003",
    investmentDate: "2026-06-10",
    fundName: "台灣科技成長基金",
    transactionNumber: "FB-002",
    currency: "TWD",
    investmentAmount: 40000,
    subscriptionFee: 120,
    subscriptionFeeCurrency: "TWD",
    subscribedUnits: 2100.75,
  },
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 10),
    fundId: "FUND-JPY-004",
    investmentDate: "2026-06-12",
    fundName: "日本不動產收益基金",
    transactionNumber: "FB-003",
    currency: "JPY",
    investmentAmount: 180000,
    subscriptionFee: 900,
    subscriptionFeeCurrency: "JPY",
    subscribedUnits: 872.13,
  },
];

const fundRedemptionTransactions: LedgerRow<"fundRedemptionTransactions">[] = [
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 4),
    fundId: "FUND-TWD-001",
    redemptionDate: "2026-06-21",
    fundName: "元大台灣卓越基金",
    transactionNumber: "FR-001",
    redemptionInvestmentAmount: 12000,
    redemptionUnits: 600.2,
    netDepositAmount: 13500,
    referencePnl: 1500,
    note: "partial redemption",
  },
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 11),
    fundId: "FUND-USD-002",
    redemptionDate: "2026-06-23",
    fundName: "全球投資級債券基金",
    transactionNumber: "FR-002",
    redemptionInvestmentAmount: 2000,
    redemptionUnits: 101.4,
    netDepositAmount: 2145,
    referencePnl: 145,
    note: "rebalance",
  },
];

const fundCashDividends: LedgerRow<"fundCashDividends">[] = [
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 5),
    fundId: "FUND-USD-002",
    depositDate: "2026-06-26",
    fundName: "全球投資級債券基金",
    transactionNumber: "FD-001",
    currency: "USD",
    distributionAmount: 82,
    distributionCurrency: "USD",
    fxRate: 32.1,
  },
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 12),
    fundId: "FUND-JPY-004",
    depositDate: "2026-06-25",
    fundName: "日本不動產收益基金",
    transactionNumber: "FD-002",
    currency: "JPY",
    distributionAmount: 4200,
    distributionCurrency: "JPY",
    fxRate: 0.22,
  },
];

const fundConversionTransactions: LedgerRow<"fundConversionTransactions">[] = [
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 6),
    queryPeriod: "2026-06",
    conversionOutDate: "2026-06-18",
    conversionInDate: "2026-06-19",
    transactionNumber: "FC-001",
    fromFundName: "穩健平衡基金",
    toFundName: "元大台灣卓越基金",
    conversionInvestmentAmount: 50000,
  },
  {
    ...common("fund.2026-06-27", "yuanta", "fund", 13),
    queryPeriod: "2026-06",
    conversionOutDate: "2026-06-22",
    conversionInDate: "2026-06-23",
    transactionNumber: "FC-002",
    fromFundName: "全球投資級債券基金",
    toFundName: "日本不動產收益基金",
    conversionInvestmentAmount: 3000,
  },
];

const brokerageHoldings: LedgerRow<"brokerageHoldings">[] = [
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 1),
    asOfDate: "2026-06-27",
    accountNumber: "BR-0001",
    assetType: "stock",
    subCategory: "listed",
    productCode: "2330",
    productName: "台積電",
    currency: "TWD",
    quantity: 200,
    marketDate: "2026-06-27",
    marketPrice: 980,
    marketValueOriginal: 196000,
    marketValueTwd: 196000,
    costPrice: 760,
    costAmount: 152000,
    unrealizedPnlOriginal: 44000,
    unrealizedPnlTwd: 44000,
    returnRate: "28.95",
    fxRate: 1,
  },
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 2),
    asOfDate: "2026-06-26",
    accountNumber: "BR-0001",
    assetType: "etf",
    subCategory: "overseas",
    productCode: "VT",
    productName: "Vanguard 全球股票 ETF",
    currency: "USD",
    quantity: 80,
    marketDate: "2026-06-26",
    marketPrice: 118.4,
    marketValueOriginal: 9472,
    marketValueTwd: 305000,
    costPrice: 105,
    costAmount: 8400,
    unrealizedPnlOriginal: 1072,
    unrealizedPnlTwd: 34500,
    returnRate: "12.76",
    fxRate: 32.2,
  },
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 6),
    asOfDate: "2026-06-25",
    accountNumber: "BR-0001",
    assetType: "etf",
    subCategory: "listed",
    productCode: "0050",
    productName: "元大台灣50",
    currency: "TWD",
    quantity: 1000,
    marketDate: "2026-06-25",
    marketPrice: 152,
    marketValueOriginal: 152000,
    marketValueTwd: 152000,
    costPrice: 160,
    costAmount: 160000,
    unrealizedPnlOriginal: -8000,
    unrealizedPnlTwd: -8000,
    returnRate: "-5.00",
    fxRate: 1,
  },
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 7),
    asOfDate: "2026-06-24",
    accountNumber: "BR-0001",
    assetType: "bond",
    subCategory: "overseas",
    productCode: "BND",
    productName: "Vanguard 美國債券 ETF",
    currency: "USD",
    quantity: 65,
    marketDate: "2026-06-24",
    marketPrice: 76.4,
    marketValueOriginal: 4966,
    marketValueTwd: 160000,
    costPrice: 73.55,
    costAmount: 4780.75,
    unrealizedPnlOriginal: 185.25,
    unrealizedPnlTwd: 6000,
    returnRate: "3.87",
    fxRate: 32.2,
  },
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 8),
    asOfDate: "2026-06-27",
    accountNumber: "BR-0001",
    assetType: "cash",
    subCategory: "settlement",
    productCode: "TWD-CASH",
    productName: "台幣交割款",
    currency: "TWD",
    quantity: 45000,
    marketDate: "2026-06-27",
    marketPrice: 1,
    marketValueOriginal: 45000,
    marketValueTwd: 45000,
    costPrice: 1,
    costAmount: 45000,
    unrealizedPnlOriginal: 0,
    unrealizedPnlTwd: 0,
    returnRate: "0.00",
    fxRate: 1,
  },
];

const brokerageTradeTransactions: LedgerRow<"brokerageTradeTransactions">[] = [
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 3),
    tradeDate: "2026-06-17",
    accountNumber: "BR-0001",
    assetType: "stock",
    tradeType: "regular",
    subCategory: "listed",
    productCode: "2330",
    productName: "台積電",
    currency: "TWD",
    action: "buy",
    quantity: 100,
    price: 960,
    grossAmount: -96000,
    fee: 137,
    tax: 0,
    settlementAmount: -96137,
    settlementCurrency: "TWD",
    realizedPnl: null,
    costAmount: 96000,
  },
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 4),
    tradeDate: "2026-06-24",
    accountNumber: "BR-0001",
    assetType: "etf",
    tradeType: "regular",
    subCategory: "overseas",
    productCode: "VT",
    productName: "Vanguard 全球股票 ETF",
    currency: "USD",
    action: "buy",
    quantity: 20,
    price: 116,
    grossAmount: -2320,
    fee: 4.99,
    tax: 0,
    settlementAmount: -2324.99,
    settlementCurrency: "USD",
    realizedPnl: null,
    costAmount: 2320,
  },
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 9),
    tradeDate: "2026-06-10",
    accountNumber: "BR-0001",
    assetType: "stock",
    tradeType: "regular",
    subCategory: "listed",
    productCode: "2454",
    productName: "聯發科",
    currency: "TWD",
    action: "sell",
    quantity: 50,
    price: 1280,
    grossAmount: 64000,
    fee: 91,
    tax: 192,
    settlementAmount: 63717,
    settlementCurrency: "TWD",
    realizedPnl: 8500,
    costAmount: 55500,
  },
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 10),
    tradeDate: "2026-06-12",
    accountNumber: "BR-0001",
    assetType: "etf",
    tradeType: "regular",
    subCategory: "listed",
    productCode: "0050",
    productName: "元大台灣50",
    currency: "TWD",
    action: "buy",
    quantity: 500,
    price: 151.5,
    grossAmount: -75750,
    fee: 108,
    tax: 0,
    settlementAmount: -75858,
    settlementCurrency: "TWD",
    realizedPnl: null,
    costAmount: 75750,
  },
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 11),
    tradeDate: "2026-06-18",
    accountNumber: "BR-0001",
    assetType: "bond",
    tradeType: "regular",
    subCategory: "overseas",
    productCode: "BND",
    productName: "Vanguard 美國債券 ETF",
    currency: "USD",
    action: "buy",
    quantity: 40,
    price: 75.8,
    grossAmount: -3032,
    fee: 4.99,
    tax: 0,
    settlementAmount: -3036.99,
    settlementCurrency: "USD",
    realizedPnl: null,
    costAmount: 3032,
  },
  {
    ...common("brokerage.2026-06-27", "yuanta-brokerage", "brokerage", 12),
    tradeDate: "2026-06-26",
    accountNumber: "BR-0001",
    assetType: "stock",
    tradeType: "regular",
    subCategory: "listed",
    productCode: "2330",
    productName: "台積電",
    currency: "TWD",
    action: "sell",
    quantity: 20,
    price: 990,
    grossAmount: 19800,
    fee: 28,
    tax: 59,
    settlementAmount: 19713,
    settlementCurrency: "TWD",
    realizedPnl: 4600,
    costAmount: 15200,
  },
];

const maicoinAccountSnapshots: LedgerRow<"maicoinAccountSnapshots">[] = [
  {
    snapshotId: "mock-btc-snapshot",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    subAccount: "main",
    walletType: "spot",
    currency: "BTC",
    balance: 0.2,
    locked: 0,
    staked: null,
    principal: null,
    interest: null,
    totalQuantity: 0.2,
    priceMarket: "btctwd",
    priceCurrency: "TWD",
    price: 2100000,
    valueTwd: 420000,
    priceAt: "2026-06-27T11:59:00.000Z",
    rawAccountJson: json({ mock: true, currency: "BTC" }),
    rawPriceJson: json({ market: "btctwd", price: 2100000 }),
    createdAt: IMPORTED_AT,
  },
  {
    snapshotId: "mock-usdt-debt-snapshot",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-25T12:00:00.000Z",
    subAccount: "main",
    walletType: "m",
    currency: "USDT",
    balance: 0,
    locked: 0,
    staked: null,
    principal: 1200,
    interest: 18,
    totalQuantity: 0,
    priceMarket: "usdttwd",
    priceCurrency: "TWD",
    price: 31.8,
    valueTwd: null,
    priceAt: "2026-06-25T11:59:00.000Z",
    rawAccountJson: json({ mock: true, currency: "USDT" }),
    rawPriceJson: json({ market: "usdttwd", price: 31.8 }),
    createdAt: IMPORTED_AT,
  },
  {
    snapshotId: "mock-eth-snapshot",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-26T12:00:00.000Z",
    subAccount: "main",
    walletType: "spot",
    currency: "ETH",
    balance: 1.4,
    locked: 0.1,
    staked: null,
    principal: null,
    interest: null,
    totalQuantity: 1.5,
    priceMarket: "ethtwd",
    priceCurrency: "TWD",
    price: 118000,
    valueTwd: 177000,
    priceAt: "2026-06-26T11:59:00.000Z",
    rawAccountJson: json({ mock: true, currency: "ETH" }),
    rawPriceJson: json({ market: "ethtwd", price: 118000 }),
    createdAt: IMPORTED_AT,
  },
  {
    snapshotId: "mock-usdc-snapshot",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    subAccount: "main",
    walletType: "spot",
    currency: "USDC",
    balance: 2500,
    locked: 0,
    staked: null,
    principal: null,
    interest: null,
    totalQuantity: 2500,
    priceMarket: "usdctwd",
    priceCurrency: "TWD",
    price: 31.7,
    valueTwd: 79250,
    priceAt: "2026-06-27T11:59:00.000Z",
    rawAccountJson: json({ mock: true, currency: "USDC" }),
    rawPriceJson: json({ market: "usdctwd", price: 31.7 }),
    createdAt: IMPORTED_AT,
  },
];

const maicoinStatementRows: LedgerRow<"maicoinStatementRows">[] = [
  {
    statementId: "mock-max-trade-btc",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    endpoint: "/api/v2/members/me/trades",
    walletType: "spot",
    rowType: "trade",
    externalId: "mock-trade-1",
    occurredAt: "2026-06-12T10:30:00.000Z",
    currency: "BTC",
    amount: 0.18,
    fee: 45,
    feeCurrency: "TWD",
    market: "btctwd",
    side: "bid",
    price: 1833333,
    valueTwd: 330000,
    rawPayloadJson: json({
      market: "btctwd",
      side: "bid",
      volume: 0.18,
      funds: 330000,
      fee_currency: "TWD",
      fee: 45,
    }),
    createdAt: IMPORTED_AT,
    updatedAt: IMPORTED_AT,
  },
  {
    statementId: "mock-max-deposit-btc",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    endpoint: "/api/v2/deposit",
    walletType: "spot",
    rowType: "deposit",
    externalId: "mock-deposit-1",
    occurredAt: "2026-06-20T10:30:00.000Z",
    currency: "BTC",
    amount: 0.02,
    fee: null,
    feeCurrency: null,
    market: null,
    side: null,
    price: null,
    valueTwd: 48000,
    rawPayloadJson: json({ currency: "BTC", amount: 0.02, state: "accepted" }),
    createdAt: IMPORTED_AT,
    updatedAt: IMPORTED_AT,
  },
  {
    statementId: "mock-max-reward-btc",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    endpoint: "/api/v2/rewards",
    walletType: "spot",
    rowType: "reward",
    externalId: "mock-reward-1",
    occurredAt: "2026-06-26T10:30:00.000Z",
    currency: "BTC",
    amount: 0.001,
    fee: null,
    feeCurrency: null,
    market: null,
    side: null,
    price: null,
    valueTwd: 2100,
    rawPayloadJson: json({ currency: "BTC", amount: 0.001, note: "staking reward" }),
    createdAt: IMPORTED_AT,
    updatedAt: IMPORTED_AT,
  },
  {
    statementId: "mock-max-trade-eth-sell",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    endpoint: "/api/v2/members/me/trades",
    walletType: "spot",
    rowType: "trade",
    externalId: "mock-trade-2",
    occurredAt: "2026-06-18T15:45:00.000Z",
    currency: "ETH",
    amount: 0.35,
    fee: 32,
    feeCurrency: "TWD",
    market: "ethtwd",
    side: "ask",
    price: 121000,
    valueTwd: 42350,
    rawPayloadJson: json({
      market: "ethtwd",
      side: "ask",
      volume: 0.35,
      funds: 42350,
      fee_currency: "TWD",
      fee: 32,
    }),
    createdAt: IMPORTED_AT,
    updatedAt: IMPORTED_AT,
  },
  {
    statementId: "mock-max-withdrawal-usdc",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    endpoint: "/api/v2/withdrawal",
    walletType: "spot",
    rowType: "withdrawal",
    externalId: "mock-withdrawal-1",
    occurredAt: "2026-06-22T08:30:00.000Z",
    currency: "USDC",
    amount: -300,
    fee: 3,
    feeCurrency: "USDC",
    market: null,
    side: null,
    price: 31.7,
    valueTwd: -9510,
    rawPayloadJson: json({ currency: "USDC", amount: 300, fee: 3, state: "accepted" }),
    createdAt: IMPORTED_AT,
    updatedAt: IMPORTED_AT,
  },
  {
    statementId: "mock-max-reward-usdc",
    syncRunId: "mock-maicoin-run",
    capturedAt: "2026-06-27T12:00:00.000Z",
    endpoint: "/api/v2/rewards",
    walletType: "m",
    rowType: "reward",
    externalId: "mock-reward-2",
    occurredAt: "2026-06-27T06:00:00.000Z",
    currency: "USDC",
    amount: 4.2,
    fee: null,
    feeCurrency: null,
    market: null,
    side: null,
    price: 31.7,
    valueTwd: 133.14,
    rawPayloadJson: json({ currency: "USDC", amount: 4.2, note: "lending reward" }),
    createdAt: IMPORTED_AT,
    updatedAt: IMPORTED_AT,
  },
];
